### ISSUE TITLE
Ability to disable debug output

### ISSUE THREAD

**Issue by mcb30** [ipxe/wimboot#1]
### Description

As a user, I would like the ability to disable debug output as a runtime choice, so that I can retain a clean user interface appearance unless I actually need to see the debug output.

### Acceptance criteria

* [x] Debug output appears as at present in standard build
* [x] Debug output may be inhibited by adding `quiet` to the `wimboot` command line

**Comment by mcb30** [comment]
Probably best implemented via a command-line option `quiet`, to avoid changing the default behaviour.

**Comment by Hammarskjold** [comment]
Looks like a great addon and shouldn't affect stability.

**Comment by mcb30** [comment]
Implemented in http://github.com/ipxe/wimboot/commit/9c576c7 and added documentation at https://ipxe.org/wimboot#disabling_debug_messages
