### ISSUE TITLE
 UEFI Grub2 how to use wimboot 

### ISSUE THREAD

**Issue by Gucan** [ipxe/wimboot#25]
Does UEFI Grub2 not use wimboot? Legacy mode is OK. It seems that UEFI mode must use ipxe, but ipxe is not friendly to local disk boot

**Comment by NiKiZe** [comment]
Wimboot is a EFI application
To use it you need:
* Support for loading files into `efifs` before starting Wimboot
* Support for starting EFI applications

Last I tried to look into this I think Grub was still missing the support to start EFI binaries.

**Comment by Gucan** [comment]
Is there any way for ipxe to load files from disk？

**Comment by NiKiZe** [comment]
Regardless, this is not an issue with wimboot, but with Grub, and you then follow up with a question about iPXE, try to look at all the information on the subject, try the search feature, and if all that fails use https://github.com/ipxe/ipxe/discussions to ask questions about iPXE.

This issue should be closed.
