### ISSUE TITLE
Update the link to wimlib in the wimboot architecture document

### ISSUE THREAD

**Issue by rgl** [ipxe/wimboot#26]
At the end of the https://ipxe.org/appnote/wimboot_architecture page there's a link to http://wimlib.sourceforge.net/. That link should be modified to https://wimlib.net/.

I can do that if you let me known at which repository I can make a PR to.

PS: Thank you for that appnote! Its quite straightforward to understand :-)

**Comment by NiKiZe** [comment]
Link updated, thanks for the report.

It is a doku wiki, and to prevent spam there is no open registration on the site.

**Comment by rgl** [comment]
Understood. Than you!
