### ISSUE TITLE
ARM32/ARM64 builds

### ISSUE THREAD

**Issue by mcb30** [ipxe/wimboot#3]
### Description

As a user I would like to be able to use wimboot on ARM platforms, so that I can boot Windows on ARM platforms using HTTP.

### Acceptance criteria

* [x] Ability to build wimboot as ~~either~~ a ~~32-bit or~~ 64-bit ARM UEFI executable
* [x] Ability to invoke the ARM wimboot executable via qemu+OVMF+iPXE

### Dependencies

* [x] ipxe/wimboot#2

**Comment by oxconan** [comment]
Hi,

do you have a plan that implement it ?

— oxconan

**Comment by bbtechlab** [comment]
Hi Jeff, I have faced the issue with clang compiler, could you please suggest ?

vanquyen@VANQUYEN2:/mnt/c/work/repos/wimboot_aarch64/src$ make -f Makefile.arm wimboot
/mnt/c/SnapdragonLLVMARM/14.1.0.0/bin/clang.exe -Os -ffreestanding -Wall -W -nostdinc -I. -fshort-wchar -DVERSION="\"v2.7.4\"" -DSBAT_GENERATION="\"1\""       -include compiler.h  -DASSEMBLY -Ui386 -E prefix.S -o prefix.aarch64.s
/mnt/c/SnapdragonLLVMARM/14.1.0.0/bin/llvm-as.exe   -o prefix.aarch64.o prefix.aarch64.s
llvm-as.exe: prefix.aarch64.s:1:1: error: expected top-level entity
# 1 "prefix.S"
^
<builtin>: recipe for target 'prefix.aarch64.o' failed
make: *** [prefix.aarch64.o] Error 1
rm prefix.aarch64.s

**Comment by mcb30** [comment]
Implemented as of commit 2a3eb91
