### ISSUE TITLE
Add .mui

### ISSUE THREAD

**Issue by nguyentumine** [ipxe/wimboot#46]
I found some systems that require a MUI file to display the Bootmgr interface

- \efi\boot\microsoft\boot\en-us\bootmgfw.efi.mui
- \boot\en-us\bootmgr.exe.mui

These folders are on the same level as the Fonts folder.  Hope this gets implemented.

Thanks.

**Comment by mcb30** [comment]
Since you have access to the systems that require this, please submit a working pull request to add the feature.  I can tidy it up for you to retest once I understand what it is you're asking for.

**Comment by nguyentumine** [comment]
I have no knowledge of C language. I am thinking that wimboot should have an extra LOCALE folder in the BOOT folder to put MUI files. bootmgr.exe.mui, memtest.exe.mui...
The folder name can be dynamically specified along with rawbcd, rawwim parameters, such as locale=en-US...

**Comment by NiKiZe** [comment]
All files available to wimboot is available in all folders.
What is the best way to reproduce the issue? Showing menu in win11 win?

Maybe we just need to extract and load all .exe.mui for all .exe / .efi that is extracted by wimboot?

**Comment by nguyentumine** [comment]
Some systems show a black screen when displaybootmenu is enabled.  When I add the file \efi\boot\microsoft\boot\en-us\bootmgfw.efi.mui the interface is displayed.  This is tested on a FAT32 physical drive.

MUI files are optional, or assume the en-US directory is also an option declared in the kernel parameter?

```
kernel gui locale=en-US
initrd efi/boot/microsoft/boot/bootmgfw.efi bootx64.efi
initrd efi/boot/microsoft/boot/en-US/bootmgfw.efi.mui bootx64.efi.mui
```

**Comment by mcb30** [comment]
@nguyentumine If you aren't able to implement a fix, then we will need a simple and unambiguous way to reproduce the problem.  What you have described so far is too vague for any code to be written or tested.

**Comment by NiKiZe** [comment]
@nguyentumine if you put the .mui file next to the .exe/.efi on your fat32 partition instead of in its locale directory, does it maybe work as well?
Normally these files are found and extracted from given .wim file, initrd commands not needed.

mcb30 there is no support for different files in different directories (everything is available in all directories)? could  it be possible to have directories available with names given by the users? (Files duplicated as with other dirs)

Possible spec:
.mui files needs to be extracted from wim (together with when other files being extracted, if they exists) and be available for any locale given (parameter/variable)

**Comment by mcb30** [comment]
> mcb30 there is no support for different files in different directories (everything is available in all directories)? could it be possible to have directories available with names given by the users? (Files duplicated as with other dirs)

It would be possible, but that would then become something that the user has to configure.  `wimboot` does extremely well so far at working with zero configuration (even to the extent of using the same binary for BIOS and UEFI), and that's not something I'd want to change.

**Comment by NiKiZe** [comment]
> > mcb30 there is no support for different files in different directories (everything is available in all directories)? could it be possible to have directories available with names given by the users? (Files duplicated as with other dirs)
> 
> It would be possible, but that would then become something that the user has to configure. `wimboot` does extremely well so far at working with zero configuration (even to the extent of using the same binary for BIOS and UEFI), and that's not something I'd want to change.

Totally agree, my thinking is extradirs=x,y,z which would generate the extra x, y and z dirs. Maybe in the root and full paths required for the dir names.

Still more data needed to make the right decisions on this.

**Comment by nguyentumine** [comment]
> @nguyentumine if you put the .mui file next to the .exe/.efi on your fat32 partition instead of in its locale directory, does it maybe work as well? 

On a physical FAT32 partition:
chainloader /path/to/bootmgfw.efi
Black screen. 
After adding /path/to/en-US/bootmgfw.efi.mui, the interface is displayed.

> Totally agree, my thinking is extradirs=x,y,z which would generate the extra x, y and z dirs. Maybe in the root and full paths required for the dir names.
> 
> Still more data needed to make the right decisions on this.

This is what I mean.

**Comment by mcb30** [comment]
> On a physical FAT32 partition: `chainloader /path/to/bootmgfw.efi` Black screen. After adding /path/to/en-US/bootmgfw.efi.mui, the interface is displayed.

@nguyentumine What do you mean by "adding" in this context? Please be a lot more precise in your explanations. We are currently having to try to guess what you might mean, which makes everything quite slow and frustrating.

**Comment by nguyentumine** [comment]
@mcb30 Sorry for my bad English, maybe I won't explain it clearly.

**Comment by mcb30** [comment]
The English is fine. 🙂  But you have missed out a lot of the important information.

You said that the command `chainloader /path/to/bootmgfw.efi` gave you a blank screen.  Great - that makes sense to me. I can guess what you might be doing, and which bootloader you might be using that has a `chainloader` command. It would be easier if you just **told** me which bootloader you were using, but no problem - I can make a good guess at this.

Then you say that you added `/path/to/en-US/bootmgfw.efi.mui`. I don't know what this means. You used a command `chainloader /path/to/en-US/bootmgfw.efi.mui`? You used a command `chainloader /path/to/bootmgfw.efi /path/to/en-US/bootmgfw.efi.mui`? You ran `cat /path/to/en-US/bootmgfw.efi.mui >>/path/to/bootmgfw.efi`? Something else?

Take a read through http://www.catb.org/~esr/faqs/smart-questions.html#translations (available in several languages) for guidance on how to submit useful issue reports.

**Comment by nguyentumine** [comment]
@mcb30 

Sorry. I use the chainloader command from Grub2, I guess the bootmgfw.efi file will read the bootmgfw.efi.mui file in the locale directory where it is located. The Fonts folder contains the ttf files and the language folders contains the mui files. I'm trying to show that we should have an extra folder to put MUI files. I think MUI files can be considered important in the Bootmgr directory tree.

**Comment by NiKiZe** [comment]
> > @nguyentumine if you put the .mui file next to the .exe/.efi on your fat32 partition instead of in its locale directory, does it maybe work as well?
> 
> On a physical FAT32 partition: `chainloader /path/to/bootmgfw.efi` Black screen. After adding /path/to/en-US/bootmgfw.efi.mui, the interface is displayed.
> 
> > Totally agree, my thinking is extradirs=x,y,z which would generate the extra x, y and z dirs. Maybe in the root and full paths required for the dir names.
> > Still more data needed to make the right decisions on this.
> 
> This is what I mean.

Does it work if you put the .mui file next to the file as well? That is without the en-US directory?

**Comment by nguyentumine** [comment]
> Does it work if you put the .mui file next to the file as well? That is without the en-US directory?

No. Now I think wimboot actually works to boot a single default entry without having to show the Bootmgr interface. MUI files will become redundant in its functionality. I would like to close this issue.

**Comment by NiKiZe** [comment]
@nguyentumine is this an issue that can reproduced with windows 10? Or in which scenario where you able to get a blank or failing menu?
