### ISSUE TITLE
XPRESS compression support

### ISSUE THREAD

**Issue by mcb30** [ipxe/wimboot#5]
As a user, I would like to be able to use WIM images that happen to be compressed using the XPRESS scheme (as an alternative to the already-supported LZX scheme), so that I don't have to worry about which compression scheme my image is using.

**Comment by RukaZhop** [comment]
It would also be great to have support for all compression types and chunk sizes supported by wimlib (https://wimlib.net/):
XPRESS: 4K, 8K, 16K, 32K, 64K
LZX: 32K, 64K, 128K, 256K, 512K, 1M, 2M
LZMS: 32K, 64K, 128K, 256K, 512K, 1M, 2M, 4M, 8M, 16M, 32M, 64M, 128M, 256M, 512M, 1G

Michael, as a developer, could you grab the decompression code from the wimlib project?

**Comment by mcb30** [comment]
> It would also be great to have support for all compression types and chunk sizes supported by wimlib (https://wimlib.net/):
> XPRESS: 4K, 8K, 16K, 32K, 64K
> LZX: 32K, 64K, 128K, 256K, 512K, 1M, 2M
> LZMS: 32K, 64K, 128K, 256K, 512K, 1M, 2M, 4M, 8M, 16M, 32M, 64M, 128M, 256M, 512M, 1G

There is no dynamic memory allocation possible within wimboot given the constraint of the operating environment, in which we have to provide a map of all required memory prior to transferring control to bootmgr.exe.  We therefore have a fixed 32kB chunk buffer, and so cannot support arbitrary chunk sizes.

> Michael, as a developer, could you grab the decompression code from the wimlib project?

Unfortunately not: userspace C code is written with the expectation of a very different operating environment than boot-time code.
