### ISSUE TITLE
wimpe based to windows 7 in  proxmox v7 and virtualbox 7 retrun blue screen

### ISSUE THREAD

**Issue by amidevous** [ipxe/wimboot#53]
wimpe based to windows 7 in  proxmox v7 retrun blue screen

please solve

wimpe based to windows 7 source and generate iso code use

```
cd /tmp
wget https://download.microsoft.com/download/4/6/C/46C337E7-336A-4199-9117-4D15D6BEC67B/KB3AIK_FR.iso
mount -o loop KB3AIK_FR.iso /mnt
mkwinpeimg --iso --arch=[amd64|x86] --waik-dir=/mnt /var/lib/tftpboot/winpe.iso
umount /mnt
```

ipxe config

```
kernel http://${server_ip}/wimboot.i386
initrd http://${server_ip}/win7/Wimpe-7-x86/BOOT/BCD         BCD
initrd http://${server_ip}/win7/Wimpe-7-x86/BOOT/BOOT.SDI    BOOT.SDI
initrd http://${server_ip}/win7/Wimpe-7-x86/SOURCES/boot.wim boot.wim
```

![image](https://github.com/ipxe/wimboot/assets/7959572/a307b5c9-68ea-48df-b8b6-e11b66807cc3)

**Comment by amidevous** [comment]
on the other hand with memdisk the boot works

only problem with memdisk is that you have to press a key

```
initrd http://${server_ip}/win7/Wimpe-7-x86.iso
chain http://${server_ip}/memdisk iso raw
boot || goto menu
```

**Comment by NiKiZe** [comment]
Is this reproducable with boot.wim without modifications using current release of wimboot ?

We are unlikely to try and reproduce this in proxmox, but if you would grab the commandline of qemu it is running it might be possible.

My guess is that you have some kind of inclusion of drivers during the creation of your winpe wim?

What this boots is winpe (not wimpe) using the boot.wim

**Comment by amidevous** [comment]
hello I have made absolutely no changes to the boot.wim file

the file I am using is the original file that is present in the original iso in the link provided to you above

and as I said the problem is present on proxmox 7

so you must already be on proxmox 7 to be able to reproduce it

this problem only occurs on proxmox 7 it does not occur on virtualbox or vmware or other

as I boot.wim it is the original file which is generated thus

```
cd /tmp
wget https://download.microsoft.com/download/4/6/C/46C337E7-336A-4199-9117-4D15D6BEC67B/KB3AIK_FR.iso
mount -o loop KB3AIK_FR.iso /mnt
mkwinpeimg --iso --arch=x86 --waik-dir=/mnt /tmp/Wimpe-7-x86.iso
umount /mnt
mkdir -p /var/www/html/win7/Wimpe-7-x86/
mount /tmp/Wimpe-7-x86.iso /mnt
cp -av /mnt/. /var/www/html/win7/Wimpe-7-x86/
```

you see a modification of the boot.wim file
in the following commands no there is none


proxmox configuration

![image](https://github.com/ipxe/wimboot/assets/7959572/3e18c315-4e6e-4086-aa9b-c3742a3c44db)

the only difference is that I had created the iso from windows

but from the same version of wimpe

i retested directly with this command

and it always returns the same error

for information it is the official iso of winpe of windows 7 in french version and not in english version

so with the keyboard and the elements of the system configured in french

the only difference with the english version is the french language pack which is added and the keyboard time zones and regional settings configured for france

official microsoft link

https://www.microsoft.com/en-us/download/details.aspx?id=5753

select french language

**Comment by amidevous** [comment]
well it's not the language that's the problem

even with the english iso same error

**Comment by amidevous** [comment]
and for the ipxe the boot is done by the iso file which is generated like this

```
cd /tmp
git clone git://git.ipxe.org/ipxe.git
cd /tmp/ipxe/src
nano /tmp/ipxe/src/chain.ipxe
```

```
#!ipxe

ifopen net0
set net0/ip 163.1x2.xxx.xxx
set net0/netmask 255.255.255.255
set net0/gateway 62.2xx.xxx.1
set dns 8.8.8.8
chain http://62.2xx.xxx.56/install.ipxe
```


```
cd /tmp/ipxe/src
make bin/ipxe.iso EMBED=chain.ipxe
cp bin/ipxe.iso /var/lib/vz/template/iso/
```

**Comment by NiKiZe** [comment]
You are using a unknown command mkwinpeimg which I assume does something?

This is probably only debuggable if you can reproduce the issue in qemu. (Run ps aux after starting the VM to grab the qemu commandline that proxmox probably is using behind the scenes)

**Comment by amidevous** [comment]
so I don't even understand what you're asking me there is no command line to manage the proxmox everything is managed from the online graphical interface and therefore from the internet browser

or if there is I don't even know how to use them

there is the ssh on the server of course but it is only used to add files to the iso folder or to manage other programs on the apache samba server etc. but for my part I have never seen or heard that there were command lines for proxmox

I have not managed anything on proxmox from the command line and I do not know of any command line allowing to manage it

me at the level of the settings all and by default as it is configured
the only thing I have changed is the settings of the virtual machine from the graphical interface and I have already given you a screenshot of the settings that are used

so if you want me to execute command lines I am willing but in this it is wrong that you indicate to me the commands in question which must be used

**Comment by NiKiZe** [comment]
Proxmox is a Linux distro, it uses qemu for virtualization, to reproduce this, it would be easier if we had that command, rather than your settings from a screenshot, which we can't copy paste.

In SSH run `ps aux | grep 101 | grep ipxe.iso`
Your VM is called 101 which is kind of hard to get a unique match on, but hopefully the combination of ipxe.iso will be enough.

But before that, could you try to just copy boot.wim from the windows ISO, and that way make sure that there is no drivers or other modifications done to the file?

**Comment by amidevous** [comment]
for this command

ps aux | grep 101 | grep ipxe.iso

no return no result

the following command

ps aux | grep 101

returns the following result


```
root         101  0.0  0.0      0     0 ?        I<   18:09   0:00 [kworker/R-blkcg]
root        1011  0.0  0.0      0     0 ?        I<   18:09   0:00 [kworker/R-rpcio]
root        1012  0.0  0.0      0     0 ?        I<   18:09   0:00 [kworker/R-xprti]
root        1314  0.1  0.0  15264 10112 ?        Ss   18:09   0:06 /usr/sbin/wpa_supplicant -c /etc/wpa_supplicant/wpa_supplicant.conf -u -s
amidevous        6583  0.0  0.0 222456  2304 pts/0    S+   19:58   0:00 grep --color=auto 101
```

the following command

ps aux | grep ipxe.iso

returns the following result

`amidevous        6589  0.0  0.0 222588  2432 pts/0    S+   19:58   0:00 grep --color=auto ipxe.iso`

Frankly, for me all this is gibberish and I absolutely do not see what it teaches us.

**Comment by amidevous** [comment]
it's weird by completely rebooting the proxmox server

and by relaunching the command I have a different result which a priori will be more useful

```
root     2013048  100  1.9 11099404 629956 ?     Sl   19:57  65:32 /usr/bin/kvm -id 101 -name 101,debug-threads=on -no-shutdown -chardev socket,id=qmp,path=/var/run/qemu-server/101.qmp,server=on,wait=off -mon chardev=qmp,mode=control -chardev socket,id=qmp-event,path=/var/run/qmeventd.sock,reconnect=5 -mon chardev=qmp-event,mode=control -pidfile /var/run/qemu-server/101.pid -daemonize -smbios type=1,uuid=b8bf9dde-68c4-49b2-beaf-6c6e246acf02 -smp 4,sockets=1,cores=4,maxcpus=4 -nodefaults -boot menu=on,strict=on,reboot-timeout=1000,splash=/usr/share/qemu-server/bootsplash.jpg -vnc unix:/var/run/qemu-server/101.vnc,password=on -no-hpet -cpu kvm64,enforce,hv_ipi,hv_relaxed,hv_reset,hv_runtime,hv_spinlocks=0x1fff,hv_stimer,hv_synic,hv_time,hv_vapic,hv_vpindex,+kvm_pv_eoi,+kvm_pv_unhalt,+lahf_lm,+sep -m 10048 -device pci-bridge,id=pci.1,chassis_nr=1,bus=pci.0,addr=0x1e -device pci-bridge,id=pci.2,chassis_nr=2,bus=pci.0,addr=0x1f -device vmgenid,guid=35b1a6b4-d8bf-48fe-a233-dadd43902ebb -device piix3-usb-uhci,id=uhci,bus=pci.0,addr=0x1.0x2 -device usb-tablet,id=tablet,bus=uhci.0,port=1 -device VGA,id=vga,bus=pci.0,addr=0x2,edid=off -device virtio-balloon-pci,id=balloon0,bus=pci.0,addr=0x3 -drive file=/var/lib/vz/images/101/vm-101-disk-0.qcow2,if=none,id=drive-ide0,cache=writeback,format=qcow2,aio=io_uring,detect-zeroes=on -device ide-hd,bus=ide.0,unit=0,drive=drive-ide0,id=ide0,rotation_rate=1,bootindex=102 -drive file=/var/lib/vz/template/iso/ipxe.iso,if=none,id=drive-ide2,media=cdrom,aio=io_uring -device ide-cd,bus=ide.1,unit=0,drive=drive-ide2,id=ide2,bootindex=100 -netdev type=tap,id=net0,ifname=tap101i0,script=/var/lib/qemu-server/pve-bridge,downscript=/var/lib/qemu-server/pve-bridgedown -device rtl8139,mac=52:54:00:01:13:9D,netdev=net0,bus=pci.0,addr=0x12,id=net0,bootindex=101 -rtc driftfix=slew,base=localtime -machine type=pc-i440fx-4.0+pve0 -global kvm-pit.lost_tick_policy=discard

```

**Comment by amidevous** [comment]
in addition you say you can't reproduce

but I just checked manually on local virtualbox

by starting on the same menu.ipxe file

and it returns exactly the same error

![image](https://github.com/ipxe/wimboot/assets/7959572/f438aa10-6abc-4b7b-bb5a-f1cb3fa5fecb)

so you absolutely cannot say that the problem is not reproductive

apart from giving these files that you could have obtained yourself by using the same commands as the one I gave you above

i don't see what else i can do

premium 1fichier link

bootmgr

https://1fichier.com/?zw8d33cclhbsw1b5tak8

boot.wim

https://1fichier.com/?21aw2a6sz1wnqvf7nu42

bcd

https://1fichier.com/?m1cl9rbd27j1f9e1hsvs

boot.sdi

https://1fichier.com/?1xncttull9aybuuo91bb

**Comment by NiKiZe** [comment]
I never said I couldn't reproduce, to be honest I haven't tried since there was insufficient data to try.

Thanks for the qemu command, and finding it reproducable in other VMs.

Still tho, you have this `mkwinpeimg` which I have no information on. There is also this gotcha of legally obtaining Isos...
Have you tried copying boot.wim from the iso without using that command that assumingly applies waik modifications?

To be clear here, I'm happy to try and help, but saying things like "that you could have obtained yourself by using the same commands as the one I gave you above" is not an attitude that will help you when asking for help.

**Comment by amidevous** [comment]
a good you are sure

`I never said I couldn't reproduce, to be honest I haven't tried since there was insufficient data to try.`

that's what you said here

`Is this reproducable with boot.wim without modifications using current release of wimboot ?`

that's why you answered that I didn't intend to offend you

so for mkwinpeimg some second on google searching

`mkwinpeimg source code`

you would have led to this

mkwinpeimg simple bash file

from the Winlib project command (which exists since 2014)

https://github.com/matchaxnb/wimlib

mkwinpeimg source code

https://github.com/matchaxnb/wimlib/blob/master/programs/mkwinpeimg.in

**Comment by NiKiZe** [comment]
> a good you are sure
> 
> `I never said I couldn't reproduce, 
> so for mkwinpeimg some second on google searching
> 
> `mkwinpeimg source code`
> 
> you would have led to this
> 
> mkwinpeimg simple bash file
> 

That is again a good way of not getting any help...
I spend my free time trying to help you, first narrowing down the issue, and getting enough info for anyone else to do the same. You have to spend the time doing the debugging, not me. For projects like these you have to be prepared to do your own debugging. If not, you should probably not even ask for help.

I again suggest that you try boot.wim from the windows original iso, without modifications.

**Comment by amidevous** [comment]
for your information I spent the whole night on this problem

and I tried all the boot.wim files of the windows aik generated from linux

the same thing with the files generated from the waik

and even those of the official windows 7 installation isos

and they all return the same errors

so since we are talking about 2 virtualization platforms

which are proxmox and virtualbox this is the proof

that a very important problem

but also that you did not even take

the trouble to properly test your program

as for the debug you are the developer

so if there is a problem it is your responsibility

to do the debug and correct

no one else can do it for you since it is your project

**Comment by NiKiZe** [comment]
No, I'm not the developer, and even if I was I would have no obligation what so ever to do your bidding.
Win7 is EOL

There is plenty of checks that validates that wimboot works properly.

**Comment by amidevous** [comment]
except that the windows 10 wimpe remains blocked on a black screen for 45 minutes while the windows 7 one has a loading bar and is displayed in less than 5 minutes while allowing you to install a windows 10

we don't have time to wait 45 minutes to launch a windows installation especially on a screen that gives the impression that everything is blocked

not to mention that on the windows 10 wimpe the x86 support has been removed while it is still present in the windows 10 installation iso

but it is a windows 10 x86 that I want to configure here

moreover even the old version of your program does not start on it and returns the same error

when you make a program like yours the responsibility is to make sure that there is at least one version that works on all official boots published by microsoft whether old or new

and that is not the case

**Comment by amidevous** [comment]
moreover to generate the iso of the winpe of windows 10 or 11

it is mandatory to be on windows as a host system

which is not the case for everyone

the adk is only published using an exe file

and this file does not even launch under wine

microsoft's fault we agree but you must take it into account in this case

while the winpe of windows 7 can be generated from any distribution that simply extracts the files that are in the cab of the isos

your program is designed to be able to start on winpe by http

this must therefore be functional from all versions of winpe

that have been officially published by microsoft

it goes from windows vista to windows 11

and it is part of your responsibility to watch over those

**Comment by mcb30** [comment]
@amidevous Your abusive behaviour is not welcome here, and I am going to block further replies to this thread. Please do not open any further discussions unless you are able to behave with civility and respect.

All wimboot commits are automatically verified as working with a wide selection of Windows versions. You can see the full list in the test directory in the source tree.

Your inability to get it working is unfortunate, but is demonstrably a problem with whatever you are doing, not a problem with the software itself.
